        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa b»ng tæng sè nh·n

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

 1  Thöa  1   Chªnh lÖch diÖn tİch
 2  Thöa  2   Chªnh lÖch diÖn tİch
 3  Thöa  3   Chªnh lÖch diÖn tİch
 4  Thöa  5   Chªnh lÖch diÖn tİch
 5  Thöa  6   Chªnh lÖch diÖn tİch
 6  Thöa  7   Chªnh lÖch diÖn tİch
 7  Thöa  8   Chªnh lÖch diÖn tİch
 8  Thöa  9   Chªnh lÖch diÖn tİch
 9  Thöa  10   Chªnh lÖch diÖn tİch
 10  Thöa  11   Chªnh lÖch diÖn tİch
 11  Thöa  12   Chªnh lÖch diÖn tİch
 12  Thöa  13   Chªnh lÖch diÖn tİch
 13  Thöa  14   Chªnh lÖch diÖn tİch
 14  Thöa  15   Chªnh lÖch diÖn tİch
 15  Thöa  16   Chªnh lÖch diÖn tİch
 16  Thöa  17   Chªnh lÖch diÖn tİch
 17  Thöa  18   Chªnh lÖch diÖn tİch
 18  Thöa  19   Chªnh lÖch diÖn tİch
 19  Thöa  20   Chªnh lÖch diÖn tİch
 20  Thöa  21   Chªnh lÖch diÖn tİch
 21  Thöa  22   Chªnh lÖch diÖn tİch
 22  Thöa  23   Chªnh lÖch diÖn tİch
 23  Thöa  24   Chªnh lÖch diÖn tİch
 24  Thöa  25   Chªnh lÖch diÖn tİch
 25  Thöa  26   Chªnh lÖch diÖn tİch
 26  Thöa  27   Chªnh lÖch diÖn tİch
 27  Thöa  28   Chªnh lÖch diÖn tİch
 28  Thöa  29   Chªnh lÖch diÖn tİch
 29  Thöa  30   Chªnh lÖch diÖn tİch
 30  Thöa  31   Chªnh lÖch diÖn tİch
 31  Thöa  32   Chªnh lÖch diÖn tİch
 32  Thöa  33   Chªnh lÖch diÖn tİch
 33  Thöa  34   Chªnh lÖch diÖn tİch
 34  Thöa  35   Chªnh lÖch diÖn tİch
 35  Thöa  36   Chªnh lÖch diÖn tİch
 36  Thöa  37   Chªnh lÖch diÖn tİch
 37  Thöa  38   Chªnh lÖch diÖn tİch
 38  Thöa  39   Chªnh lÖch diÖn tİch
 39  Thöa  41   Chªnh lÖch diÖn tİch
 40  Thöa  42   Chªnh lÖch diÖn tİch
 41  Thöa  43   Chªnh lÖch diÖn tİch
 42  Thöa  44   Chªnh lÖch diÖn tİch
 43  Thöa  45   Chªnh lÖch diÖn tİch
 44  Thöa  46   Chªnh lÖch diÖn tİch
 45  Thöa  47  Kh«ng cã nh·n
 46  Thöa  48   Chªnh lÖch diÖn tİch
 47  Thöa  49   Chªnh lÖch diÖn tİch
 48  Thöa  50   Chªnh lÖch diÖn tİch
 49  Thöa  51   Chªnh lÖch diÖn tİch
 50  Thöa  52   Chªnh lÖch diÖn tİch
 51  Thöa  53   Chªnh lÖch diÖn tİch
 52  Thöa  54   Chªnh lÖch diÖn tİch
 53  Thöa  55   Chªnh lÖch diÖn tİch
 54  Thöa  56   Chªnh lÖch diÖn tİch
 55  Thöa  57   Chªnh lÖch diÖn tİch
 56  Thöa  58   Chªnh lÖch diÖn tİch
 57  Thöa  59   Chªnh lÖch diÖn tİch
 58  Thöa  60   Chªnh lÖch diÖn tİch
 59  Thöa  62   Chªnh lÖch diÖn tİch
 60  Thöa  63   Chªnh lÖch diÖn tİch
 61  Thöa  64   Chªnh lÖch diÖn tİch
 62  Thöa  65   Chªnh lÖch diÖn tİch
 63  Thöa  66   Chªnh lÖch diÖn tİch
 64  Thöa  67   Chªnh lÖch diÖn tİch
 65  Thöa  68   Chªnh lÖch diÖn tİch
 66  Thöa  69   Chªnh lÖch diÖn tİch
 67  Thöa  70   Chªnh lÖch diÖn tİch
 68  Thöa  71   Chªnh lÖch diÖn tİch
 69  Thöa  72   Chªnh lÖch diÖn tİch
 70  Thöa  73   Chªnh lÖch diÖn tİch
 71  Thöa  74   Chªnh lÖch diÖn tİch
 72  Thöa  75   Chªnh lÖch diÖn tİch
 73  Thöa  76   Chªnh lÖch diÖn tİch
 74  Thöa  77   Chªnh lÖch diÖn tİch
 75  Thöa  79   Chªnh lÖch diÖn tİch
 76  Thöa  80   Chªnh lÖch diÖn tİch
 77  Thöa  81   Chªnh lÖch diÖn tİch
 78  Thöa  82   Chªnh lÖch diÖn tİch
 79  Thöa  83   Chªnh lÖch diÖn tİch
 80  Thöa  84   Chªnh lÖch diÖn tİch
 81  Thöa  85   Chªnh lÖch diÖn tİch
 82  Thöa  86   Chªnh lÖch diÖn tİch
 83  Thöa  87   Chªnh lÖch diÖn tİch
 84  Thöa  88   Chªnh lÖch diÖn tİch
 85  Thöa  89   Chªnh lÖch diÖn tİch
 86  Thöa  90   Chªnh lÖch diÖn tİch
 87  Thöa  91   Chªnh lÖch diÖn tİch
 88  Thöa  92   Chªnh lÖch diÖn tİch
 89  Thöa  93   Chªnh lÖch diÖn tİch
 90  Thöa  94   Chªnh lÖch diÖn tİch
 91  Thöa  95   Chªnh lÖch diÖn tİch
 92  Thöa  96   Chªnh lÖch diÖn tİch
 93  Thöa  97   Chªnh lÖch diÖn tİch
 94  Thöa  98   Chªnh lÖch diÖn tİch
 95  Thöa  99   Chªnh lÖch diÖn tİch
 96  Thöa  100   Chªnh lÖch diÖn tİch
 97  Thöa  101  Kh«ng cã nh·n
 98  Thöa  102   Chªnh lÖch diÖn tİch
 99  Thöa  103   Chªnh lÖch diÖn tİch
 100  Thöa  104   Chªnh lÖch diÖn tİch
 101  Thöa  105   Chªnh lÖch diÖn tİch
 102  Thöa  106   Chªnh lÖch diÖn tİch
 103  Thöa  107   Chªnh lÖch diÖn tİch
 104  Thöa  108   Chªnh lÖch diÖn tİch
 105  Thöa  109   Chªnh lÖch diÖn tİch
 106  Thöa  110   Chªnh lÖch diÖn tİch
 107  Thöa  111   Chªnh lÖch diÖn tİch
 108  Thöa  112   Chªnh lÖch diÖn tİch
 109  Thöa  113   Chªnh lÖch diÖn tİch
 110  Thöa  114   Chªnh lÖch diÖn tİch
 111  Thöa  115   Chªnh lÖch diÖn tİch
 112  Thöa  116   Chªnh lÖch diÖn tİch
 113  Thöa  117   Chªnh lÖch diÖn tİch
 114  Thöa  118   Chªnh lÖch diÖn tİch
 115  Thöa  119   Chªnh lÖch diÖn tİch
 116  Thöa  120   Chªnh lÖch diÖn tİch
 117  Thöa  121   Chªnh lÖch diÖn tİch
 118  Thöa  122   Chªnh lÖch diÖn tİch
 119  Thöa  123   Chªnh lÖch diÖn tİch
 120  Thöa  124   Chªnh lÖch diÖn tİch
 121  Thöa  125   Chªnh lÖch diÖn tİch
 122  Thöa  126   Chªnh lÖch diÖn tİch

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

 1  Kh«ng cã thöa   0  trong file txt
 2  Kh«ng cã thöa   0  trong file txt
