        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa b»ng tæng sè nh·n

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

 1  Thöa  1   Chªnh lÖch diÖn tİch
 2  Thöa  3   Chªnh lÖch diÖn tİch
 3  Thöa  4   Chªnh lÖch diÖn tİch
 4  Thöa  5   Chªnh lÖch diÖn tİch
 5  Thöa  6   Chªnh lÖch diÖn tİch
 6  Thöa  8   Chªnh lÖch diÖn tİch
 7  Thöa  9   Chªnh lÖch diÖn tİch
 8  Thöa  10   Chªnh lÖch diÖn tİch
 9  Thöa  11   Chªnh lÖch diÖn tİch
 10  Thöa  13   Chªnh lÖch diÖn tİch
 11  Thöa  16   Chªnh lÖch diÖn tİch
 12  Thöa  17   Chªnh lÖch diÖn tİch
 13  Thöa  18   Chªnh lÖch diÖn tİch
 14  Thöa  19   Chªnh lÖch diÖn tİch
 15  Thöa  20   Chªnh lÖch diÖn tİch
 16  Thöa  21   Chªnh lÖch diÖn tİch
 17  Thöa  23   Chªnh lÖch diÖn tİch
 18  Thöa  25   Chªnh lÖch diÖn tİch
 19  Thöa  26   Chªnh lÖch diÖn tİch
 20  Thöa  27   Chªnh lÖch diÖn tİch
 21  Thöa  28   Chªnh lÖch diÖn tİch
 22  Thöa  29   Chªnh lÖch diÖn tİch
 23  Thöa  30   Chªnh lÖch diÖn tİch
 24  Thöa  31   Chªnh lÖch diÖn tİch
 25  Thöa  32   Chªnh lÖch diÖn tİch
 26  Thöa  33   Chªnh lÖch diÖn tİch
 27  Thöa  34   Chªnh lÖch diÖn tİch
 28  Thöa  35   Chªnh lÖch diÖn tİch
 29  Thöa  36   Chªnh lÖch diÖn tİch
 30  Thöa  37   Chªnh lÖch diÖn tİch
 31  Thöa  38   Chªnh lÖch diÖn tİch
 32  Thöa  39   Chªnh lÖch diÖn tİch
 33  Thöa  40   Chªnh lÖch diÖn tİch
 34  Thöa  41   Chªnh lÖch diÖn tİch
 35  Thöa  42   Chªnh lÖch diÖn tİch
 36  Thöa  43   Chªnh lÖch diÖn tİch
 37  Thöa  44   Chªnh lÖch diÖn tİch
 38  Thöa  45   Chªnh lÖch diÖn tİch
 39  Thöa  46   Chªnh lÖch diÖn tİch
 40  Thöa  47   Chªnh lÖch diÖn tİch
 41  Thöa  48   Chªnh lÖch diÖn tİch
 42  Thöa  49   Chªnh lÖch diÖn tİch
 43  Thöa  50   Chªnh lÖch diÖn tİch
 44  Thöa  51   Chªnh lÖch diÖn tİch
 45  Thöa  52   Chªnh lÖch diÖn tİch
 46  Thöa  53   Chªnh lÖch diÖn tİch
 47  Thöa  54   Chªnh lÖch diÖn tİch
 48  Thöa  55   Chªnh lÖch diÖn tİch
 49  Thöa  56   Chªnh lÖch diÖn tİch
 50  Thöa  57   Chªnh lÖch diÖn tİch
 51  Thöa  58   Chªnh lÖch diÖn tİch
 52  Thöa  60   Chªnh lÖch diÖn tİch
 53  Thöa  62   Chªnh lÖch diÖn tİch
 54  Thöa  63   Chªnh lÖch diÖn tİch
 55  Thöa  64   Chªnh lÖch diÖn tİch
 56  Thöa  65  Chªnh lÖch lo¹i ®Êt
 57  Thöa  66   Chªnh lÖch diÖn tİch
 58  Thöa  67   Chªnh lÖch diÖn tİch
 59  Thöa  68   Chªnh lÖch diÖn tİch
 60  Thöa  69   Chªnh lÖch diÖn tİch

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

Chóc mõng b¹n kh«ng cã lçi nµy
