        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa nhá h¬n tæng sè nh·n:   24  thöa

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

Chóc mõng b¹n kh«ng cã lçi nµy

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

 1  Kh«ng cã thöa   1  trong file txt
 2  Kh«ng cã thöa   2  trong file txt
 3  Kh«ng cã thöa   3  trong file txt
 4  Kh«ng cã thöa   4  trong file txt
 5  Kh«ng cã thöa   5  trong file txt
 6  Kh«ng cã thöa   6  trong file txt
 7  Kh«ng cã thöa   7  trong file txt
 8  Kh«ng cã thöa   8  trong file txt
 9  Kh«ng cã thöa   9  trong file txt
 10  Kh«ng cã thöa   10  trong file txt
 11  Kh«ng cã thöa   11  trong file txt
 12  Kh«ng cã thöa   12  trong file txt
 13  Kh«ng cã thöa   13  trong file txt
 14  Kh«ng cã thöa   14  trong file txt
 15  Kh«ng cã thöa   15  trong file txt
 16  Kh«ng cã thöa   16  trong file txt
 17  Kh«ng cã thöa   17  trong file txt
 18  Kh«ng cã thöa   18  trong file txt
 19  Kh«ng cã thöa   19  trong file txt
 20  Kh«ng cã thöa   20  trong file txt
 21  Kh«ng cã thöa   21  trong file txt
 22  Kh«ng cã thöa   22  trong file txt
 23  Kh«ng cã thöa   23  trong file txt
 24  Kh«ng cã thöa   24  trong file txt
