        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa b»ng tæng sè nh·n

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

 1  Thöa  25  Kh«ng cã nh·n
 2  Thöa  41  Kh«ng cã nh·n
 3  Thöa  61  Kh«ng cã nh·n
 4  Thöa  103  Kh«ng cã nh·n

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

 1  Kh«ng cã thöa   0  trong file txt
 2  Kh«ng cã thöa   0  trong file txt
 3  Kh«ng cã thöa   0  trong file txt
 4  Kh«ng cã thöa   0  trong file txt
