        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa b»ng tæng sè nh·n

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

 1  Thöa  55  Kh«ng cã nh·n
 2  Thöa  81  Kh«ng cã nh·n
 3  Thöa  92  Kh«ng cã nh·n

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

 1  Kh«ng cã thöa   0  trong file txt
 2  Kh«ng cã thöa   0  trong file txt
 3  Kh«ng cã thöa   0  trong file txt
