        KiÓm tra th«ng tin trong file txt vµ nh·n thöa

        Tæng sè thöa b»ng tæng sè nh·n

------------------------------------------------------
KiÓm tra file txt so víi nh·n thöa

 1  Thöa  22   Chªnh lÖch diÖn tİch
 2  Thöa  44   Chªnh lÖch diÖn tİch
 3  Thöa  45   Chªnh lÖch diÖn tİch

------------------------------------------------------
KiÓm tra nh·n thöa so víi file txt

Chóc mõng b¹n kh«ng cã lçi nµy
